<?php
$app = require __DIR__ . '/../config/config.php';
?><!doctype html>
<html lang="pt-PT">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= htmlspecialchars($app['app']['name']) ?></title>
<style>
:root{--bg:#f4f7fb;--card:#fff;--text:#172033;--muted:#6b7280;--line:#e5e7eb;--primary:#2563eb;--dark:#111827}
*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Arial;background:var(--bg);color:var(--text)}
.layout{display:flex;min-height:100vh}.side{width:245px;background:var(--dark);color:#fff;padding:20px;position:fixed;height:100vh}.brand{font-size:21px;font-weight:800;margin-bottom:22px}.brand b{color:#60a5fa}.nav button{display:block;width:100%;background:none;border:0;color:#d1d5db;text-align:left;padding:10px;border-radius:8px;margin:3px 0;cursor:pointer}.nav button:hover,.nav button.on{background:#1f2937;color:white}.main{margin-left:245px;width:calc(100% - 245px)}header{height:64px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 25px;position:sticky;top:0;z-index:2}.content{padding:25px;max-width:1500px;margin:auto}.page{display:none}.page.on{display:block}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.head h1{margin:0}.btn{background:var(--primary);color:#fff;border:0;border-radius:8px;padding:10px 14px;font-weight:700;cursor:pointer}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.panel{background:#fff;border:1px solid var(--line);border-radius:12px;padding:17px}.kpi{font-size:28px;font-weight:800;margin-top:5px}.muted{color:var(--muted);font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid var(--line);text-align:left;font-size:13px}th{background:#f8fafc}.badge{padding:4px 8px;border-radius:99px;font-size:11px;font-weight:700}.blue{background:#dbeafe;color:#1e40af}.red{background:#fee2e2;color:#991b1b}.green{background:#dcfce7;color:#166534}.yellow{background:#fef3c7;color:#92400e}.modal{display:none;position:fixed;inset:0;background:#0008;align-items:center;justify-content:center;z-index:10}.modal.open{display:flex}.box{background:white;padding:22px;border-radius:12px;width:min(650px,94vw)}form{display:grid;grid-template-columns:1fr 1fr;gap:10px}input,select{padding:10px;border:1px solid var(--line);border-radius:7px}.full{grid-column:1/-1}@media(max-width:850px){.side{transform:translateX(-100%)}.side.open{transform:none}.main{margin-left:0;width:100%}.cards{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}@media(max-width:520px){.cards{grid-template-columns:1fr}.content{padding:14px}form{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="layout">
<aside class="side" id="side"><div class="brand">Maint<b>Pro</b> EAM</div><nav class="nav">
<button class="on" data-page="dashboard">▣ Dashboard</button><button data-page="assets">▣ Ativos</button><button data-page="notifications">⚠ Notificações</button><button data-page="orders">▤ Ordens</button><button data-page="planning">◫ PCM</button><button data-page="predictive">◉ Preditiva</button><button data-page="reliability">◇ Reliability</button><button data-page="spares">▣ Sobressalentes</button>
</nav></aside>
<main class="main"><header><button class="btn" onclick="document.getElementById('side').classList.toggle('open')">☰</button><strong>Gestão de Manutenção Industrial</strong><span class="muted">v1.0</span></header>
<div class="content">
<section id="dashboard" class="page on"><div class="head"><h1>Dashboard</h1><button class="btn" onclick="openM('order')">+ Nova ordem</button></div><div class="cards"><div class="card"><div class="muted">Ativos</div><div class="kpi" id="kAssets">-</div></div><div class="card"><div class="muted">Ordens</div><div class="kpi" id="kOrders">-</div></div><div class="card"><div class="muted">Ordens abertas</div><div class="kpi" id="kOpen">-</div></div><div class="card"><div class="muted">Notificações abertas</div><div class="kpi" id="kNotif">-</div></div></div><div class="grid"><div class="panel"><h3>Indicadores de referência</h3><p>Disponibilidade <b>96,4%</b></p><p>MTBF <b>428 h</b></p><p>MTTR <b>3,6 h</b></p><p>Schedule Compliance <b>91%</b></p></div><div class="panel"><h3>Fluxo MaintPro</h3><p class="muted">Ativo → Notificação → Planeamento → Ordem → Execução → Material → Custo → Histórico → KPI → RCA.</p></div></div></section>
<section id="assets" class="page"><div class="head"><h1>Ativos</h1><button class="btn" onclick="openM('asset')">+ Ativo</button></div><div class="panel"><table><thead><tr><th>Tag</th><th>Nome</th><th>Tipo</th><th>Localização</th><th>Criticidade</th><th>Estado</th></tr></thead><tbody id="assetsBody"></tbody></table></div></section>
<section id="notifications" class="page"><div class="head"><h1>Notificações</h1><button class="btn" onclick="openM('notification')">+ Notificação</button></div><div class="panel"><table><thead><tr><th>Nº</th><th>Ativo</th><th>Descrição</th><th>Prioridade</th><th>Estado</th></tr></thead><tbody id="notificationsBody"></tbody></table></div></section>
<section id="orders" class="page"><div class="head"><h1>Ordens de Manutenção</h1><button class="btn" onclick="openM('order')">+ Ordem</button></div><div class="panel"><table><thead><tr><th>Nº</th><th>Ativo</th><th>Descrição</th><th>Tipo</th><th>Prioridade</th><th>Estado</th></tr></thead><tbody id="ordersBody"></tbody></table></div></section>
<section id="planning" class="page"><div class="head"><h1>PCM / Planeamento</h1></div><div class="cards"><div class="card"><div class="muted">Backlog</div><div class="kpi">47</div></div><div class="card"><div class="muted">Ready to Schedule</div><div class="kpi">19</div></div><div class="card"><div class="muted">Carga</div><div class="kpi">148 h</div></div><div class="card"><div class="muted">Compliance</div><div class="kpi">91%</div></div></div></section>
<section id="predictive" class="page"><div class="head"><h1>Condition Monitoring</h1></div><div class="grid"><div class="panel"><h3>Vibração</h3><p>M-101 — 4,8 mm/s <span class="badge yellow">Alerta</span></p><p>P-101 — 6,2 mm/s <span class="badge red">Crítico</span></p></div><div class="panel"><h3>Temperatura</h3><p>P-101 — 78 °C <span class="badge red">Crítico</span></p><p>M-101 — 62 °C <span class="badge green">Normal</span></p></div></div></section>
<section id="reliability" class="page"><div class="head"><h1>Reliability / RCM / FMEA / RCA</h1></div><div class="cards"><div class="card"><div class="muted">MTBF</div><div class="kpi">428 h</div></div><div class="card"><div class="muted">MTTR</div><div class="kpi">3,6 h</div></div><div class="card"><div class="muted">RCM</div><div class="kpi">18</div></div><div class="card"><div class="muted">RCA abertas</div><div class="kpi">6</div></div></div></section>
<section id="spares" class="page"><div class="head"><h1>Sobressalentes</h1></div><div class="panel"><table><tr><th>Código</th><th>Descrição</th><th>Stock</th><th>Mínimo</th><th>Lead Time</th></tr><tr><td>BRG-6312</td><td>Rolamento 6312</td><td>4</td><td>2</td><td>15 dias</td></tr><tr><td>SEAL-101</td><td>Selo mecânico P-101</td><td>0</td><td>1</td><td>30 dias</td></tr></table></div></section>
</div></main></div>

<div class="modal" id="asset"><div class="box"><h2>Novo ativo</h2><form id="assetForm"><input id="atag" placeholder="Tag" required><input id="aname" placeholder="Nome" required><input id="atype" placeholder="Tipo" required><input id="aloc" placeholder="Localização"><select id="acrit"><option>A</option><option>B</option><option>C</option></select><select id="astatus"><option>Operacional</option><option>Parado</option><option>Em manutenção</option></select><button class="btn full">Guardar</button></form></div></div>
<div class="modal" id="notification"><div class="box"><h2>Nova notificação</h2><form id="notificationForm"><input id="nasset" placeholder="ID do ativo"><input id="npriority" value="P3" placeholder="Prioridade"><input id="ndesc" class="full" placeholder="Descrição" required><button class="btn full">Guardar</button></form></div></div>
<div class="modal" id="order"><div class="box"><h2>Nova ordem</h2><form id="orderForm"><input id="oasset" placeholder="ID do ativo"><input id="opriority" value="P3" placeholder="Prioridade"><input id="otype" value="Corretiva" placeholder="Tipo"><input id="ohours" type="number" step="0.5" value="0" placeholder="Horas planeadas"><input id="odesc" class="full" placeholder="Descrição" required><button class="btn full">Guardar</button></form></div></div>
<script>
const api='../api/';
const $=id=>document.getElementById(id);
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));$(b.dataset.page).classList.add('on');$('side').classList.remove('open');load()});
function openM(id){$(id).classList.add('open')} function closeM(id){$(id).classList.remove('open')}
document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});
async function get(path){let r=await fetch(api+path);return r.json()}
async function load(){
 try{
 let d=await get('dashboard.php'); if(d.ok){$('kAssets').textContent=d.data.assets;$('kOrders').textContent=d.data.orders;$('kOpen').textContent=d.data.open_orders;$('kNotif').textContent=d.data.open_notifications}
 let a=await get('assets.php'); if(a.ok)$('assetsBody').innerHTML=a.data.map(x=>`<tr><td><b>${x.tag}</b></td><td>${x.name}</td><td>${x.type}</td><td>${x.location||''}</td><td><span class="badge ${x.criticality==='A'?'red':'yellow'}">${x.criticality}</span></td><td>${x.status}</td></tr>`).join('');
 let n=await get('notifications.php'); if(n.ok)$('notificationsBody').innerHTML=n.data.map(x=>`<tr><td>${x.notification_no}</td><td>${x.asset_tag||'-'}</td><td>${x.description}</td><td>${x.priority}</td><td>${x.status}</td></tr>`).join('');
 let o=await get('orders.php'); if(o.ok)$('ordersBody').innerHTML=o.data.map(x=>`<tr><td>${x.order_no}</td><td>${x.asset_tag||'-'}</td><td>${x.description}</td><td>${x.type}</td><td>${x.priority}</td><td>${x.status}</td></tr>`).join('');
 }catch(e){console.error(e)}
}
async function post(endpoint,data){let r=await fetch(api+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return r.json()}
$('assetForm').onsubmit=async e=>{e.preventDefault();let r=await post('assets.php',{tag:$('atag').value,name:$('aname').value,type:$('atype').value,location:$('aloc').value,criticality:$('acrit').value,status:$('astatus').value});if(r.ok){closeM('asset');e.target.reset();load()}else alert(r.error||'Erro')};
$('notificationForm').onsubmit=async e=>{e.preventDefault();let r=await post('notifications.php',{asset_id:$('nasset').value||null,description:$('ndesc').value,priority:$('npriority').value});if(r.ok){closeM('notification');e.target.reset();load()}else alert(r.error||'Erro')};
$('orderForm').onsubmit=async e=>{e.preventDefault();let r=await post('orders.php',{asset_id:$('oasset').value||null,description:$('odesc').value,type:$('otype').value,priority:$('opriority').value,planned_hours:$('ohours').value});if(r.ok){closeM('order');e.target.reset();load()}else alert(r.error||'Erro')};
load();
</script>
</body></html>